[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 0.7 
blur = false

[font]
normal = { family = "MesloLGS NF", style = "Italic" }

[terminal]
osc52 = "CopyPaste"

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_timeout = 60
blink_interval = 500

[keyboard]
bindings = [
        {key = "q", mods = "Alt", action = "Quit"},
        {key = "c", mods = "Alt", action = "Copy"},
        {key = "v", mods = "Alt", action = "Paste"},
        {key = "f", mods = "Alt", action = "ToggleMaximized"},
        {key = "Return", mods = "Alt", action = "CreateNewWindow"},
]
